name=MiP Power Up - Pro Mini
version=2.0.0
author=Samuel Trassare <tiogaplanet@users.noreply.github.com>
maintainer=Samuel Trassare <tiogaplanet@users.noreply.github.com>
sentence=Control the WowWee MiP robot from an Arduino Pro Mini.
paragraph=This library, together with MiP Pwer Up - Pro mini adapter board, lets you access MiP and control its motion, sensors, sound, LEDs, and more.
category=Device Control
url=https://github.com/Tiogaplanet/MPU_Pro_Mini_lib
architectures=avr
includes=MiP_Power_Up_-_Pro_Mini.h
